webtalk_init -webtalk_dir C:/Users/ifaaz/Desktop/Lab DIGITAL SYSTEM DESIGN/22-cp-47 CEP/solution/solution.sim/sim_1/behav/xsim/xsim.dir/mips_processor_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 21 23:40:46 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "083eceac-1d51-489e-8183-838f778a5882" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "27bc2c2c22604b65a913835f911ab308" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9292_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1732990198 -regid "" -xml C:/Users/ifaaz/Desktop/Lab DIGITAL SYSTEM DESIGN/22-cp-47 CEP/solution/solution.sim/sim_1/behav/xsim/xsim.dir/mips_processor_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ifaaz/Desktop/Lab DIGITAL SYSTEM DESIGN/22-cp-47 CEP/solution/solution.sim/sim_1/behav/xsim/xsim.dir/mips_processor_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ifaaz/Desktop/Lab DIGITAL SYSTEM DESIGN/22-cp-47 CEP/solution/solution.sim/sim_1/behav/xsim/xsim.dir/mips_processor_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
